imageType:
  Original: {}
  Wavelet:
      binWidth: 10

featureClass:
<<<<<<< Updated upstream
  firstorder: []
  glcm: []
  glrlm: []
  glszm: []
  ngtdm: []
=======
  glcm: []
  glrlm: []
  firstorder: []
>>>>>>> Stashed changes
  shape: []

setting:
  binWidth: 25